/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedMapRouteImport } from './routes/_authenticated/map'
import { Route as AuthenticatedVehiclesIndexRouteImport } from './routes/_authenticated/vehicles.index'
import { Route as AuthenticatedVehiclesIdIndexRouteImport } from './routes/_authenticated/vehicles.$id.index'
import { Route as AuthenticatedVehiclesIdPlaybackRouteImport } from './routes/_authenticated/vehicles.$id.playback'
import { Route as AuthenticatedVehiclesIdHistoryRouteImport } from './routes/_authenticated/vehicles.$id.history'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMapRoute = AuthenticatedMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVehiclesIndexRoute =
  AuthenticatedVehiclesIndexRouteImport.update({
    id: '/vehicles/',
    path: '/vehicles/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVehiclesIdIndexRoute =
  AuthenticatedVehiclesIdIndexRouteImport.update({
    id: '/vehicles/$id/',
    path: '/vehicles/$id/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVehiclesIdPlaybackRoute =
  AuthenticatedVehiclesIdPlaybackRouteImport.update({
    id: '/vehicles/$id/playback',
    path: '/vehicles/$id/playback',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVehiclesIdHistoryRoute =
  AuthenticatedVehiclesIdHistoryRouteImport.update({
    id: '/vehicles/$id/history',
    path: '/vehicles/$id/history',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/map': typeof AuthenticatedMapRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/users': typeof AuthenticatedUsersRoute
  '/vehicles/': typeof AuthenticatedVehiclesIndexRoute
  '/vehicles/$id/history': typeof AuthenticatedVehiclesIdHistoryRoute
  '/vehicles/$id/playback': typeof AuthenticatedVehiclesIdPlaybackRoute
  '/vehicles/$id/': typeof AuthenticatedVehiclesIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/map': typeof AuthenticatedMapRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/users': typeof AuthenticatedUsersRoute
  '/': typeof AuthenticatedIndexRoute
  '/vehicles': typeof AuthenticatedVehiclesIndexRoute
  '/vehicles/$id/history': typeof AuthenticatedVehiclesIdHistoryRoute
  '/vehicles/$id/playback': typeof AuthenticatedVehiclesIdPlaybackRoute
  '/vehicles/$id': typeof AuthenticatedVehiclesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/map': typeof AuthenticatedMapRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/vehicles/': typeof AuthenticatedVehiclesIndexRoute
  '/_authenticated/vehicles/$id/history': typeof AuthenticatedVehiclesIdHistoryRoute
  '/_authenticated/vehicles/$id/playback': typeof AuthenticatedVehiclesIdPlaybackRoute
  '/_authenticated/vehicles/$id/': typeof AuthenticatedVehiclesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/sitemap.xml'
    | '/map'
    | '/profile'
    | '/users'
    | '/vehicles/'
    | '/vehicles/$id/history'
    | '/vehicles/$id/playback'
    | '/vehicles/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/sitemap.xml'
    | '/map'
    | '/profile'
    | '/users'
    | '/'
    | '/vehicles'
    | '/vehicles/$id/history'
    | '/vehicles/$id/playback'
    | '/vehicles/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/sitemap.xml'
    | '/_authenticated/map'
    | '/_authenticated/profile'
    | '/_authenticated/users'
    | '/_authenticated/'
    | '/_authenticated/vehicles/'
    | '/_authenticated/vehicles/$id/history'
    | '/_authenticated/vehicles/$id/playback'
    | '/_authenticated/vehicles/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/map': {
      id: '/_authenticated/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof AuthenticatedMapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vehicles/': {
      id: '/_authenticated/vehicles/'
      path: '/vehicles'
      fullPath: '/vehicles/'
      preLoaderRoute: typeof AuthenticatedVehiclesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vehicles/$id/': {
      id: '/_authenticated/vehicles/$id/'
      path: '/vehicles/$id'
      fullPath: '/vehicles/$id/'
      preLoaderRoute: typeof AuthenticatedVehiclesIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vehicles/$id/playback': {
      id: '/_authenticated/vehicles/$id/playback'
      path: '/vehicles/$id/playback'
      fullPath: '/vehicles/$id/playback'
      preLoaderRoute: typeof AuthenticatedVehiclesIdPlaybackRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vehicles/$id/history': {
      id: '/_authenticated/vehicles/$id/history'
      path: '/vehicles/$id/history'
      fullPath: '/vehicles/$id/history'
      preLoaderRoute: typeof AuthenticatedVehiclesIdHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedMapRoute: typeof AuthenticatedMapRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedVehiclesIndexRoute: typeof AuthenticatedVehiclesIndexRoute
  AuthenticatedVehiclesIdHistoryRoute: typeof AuthenticatedVehiclesIdHistoryRoute
  AuthenticatedVehiclesIdPlaybackRoute: typeof AuthenticatedVehiclesIdPlaybackRoute
  AuthenticatedVehiclesIdIndexRoute: typeof AuthenticatedVehiclesIdIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedMapRoute: AuthenticatedMapRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedVehiclesIndexRoute: AuthenticatedVehiclesIndexRoute,
  AuthenticatedVehiclesIdHistoryRoute: AuthenticatedVehiclesIdHistoryRoute,
  AuthenticatedVehiclesIdPlaybackRoute: AuthenticatedVehiclesIdPlaybackRoute,
  AuthenticatedVehiclesIdIndexRoute: AuthenticatedVehiclesIdIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
